### ISSUE TITLE
Too much view padding + moving the view

### ISSUE THREAD

**Issue by dimateos** [Tzanou123/vscode_tamagotchi_extension#3]
Hey! first of all, great idea for a extension :)
First thing similar to vscode-pets that Ive seen and I love vscode-pets!

There seem to be too much padding around the game view, for example compared with pets:

![image](https://github.com/tzanou-perso/vscode_tamagotchi_extension/assets/26868611/d692df63-c566-4f8d-889f-0b822cf65aa2)

Also, if I move the view to another panel it crashes and vscode window needs to be reloaded to restart it properly:
> You can move it around in the same panel, but in my case I moved from the explorer panel (left) to my rigth side panel. I can give you more info if you cannot reproduce it. Not as important as I dont plan to move around constantly tho.

![image](https://github.com/tzanou-perso/vscode_tamagotchi_extension/assets/26868611/a713f2de-405f-461b-ba3a-daf24eb3c1ff)

**Comment by Tzanou123** [comment]
Hello, 
Thanks for your feedback and happy you like the extension. 
I plan to fix those bugs in next release, probably on this end of weeks.

**Comment by Tzanou123** [comment]
I upload a new release with patching the problem you relate ! Can you confirm after update the problems are gone ? I can then merge the branch ! 
Thanks

**Comment by dimateos** [comment]
Sure!

1. The window no longer stops working when moving the view around
2. The padding is gone

This is how it looks on my end:

![2024-03-07_(170454)_Code](https://github.com/tzanou-perso/vscode_tamagotchi_extension/assets/26868611/71291a8d-895a-431f-b2e1-dd022ce7ae29)

> I guess you had to do funky things with the aspect ratio stuff to fit the view with no padding at all. I think you did a nice job!

Only tiny issue is that now (as you can see in the gif), the text and sprites are over-scaled by a bit in the vertical axis when the aspect ratio is mainly horizontal.

* One thing to note, vs-code pets does not scale but repeat textures (only horizontally). I you want to avoid scaling the background too much, you could have a backgraound that is tileable horizontally and a sky that tiles vertically too. But not very important IMO, nobody is going to make the view huge.
* **But IMO making the sprites/text look normal in tiny views matters.** Tiny views are something that I would actually keep open while coding!

**Comment by Tzanou123** [comment]
Thanks dude, your feedback are really appreciated.
I fix the bug you pointed to me in the new version!
